version: "3"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: aeiou123
      POSTGRES_DB: fastapi

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      POSTGRES_DB: fastapi
      POSTGRES_USER: postgres
      POSTGRES_PASS: aeiou123
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
    - 1080:1080
       
